import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [location, setLocation] = useState(``);
  const [data, setData] = useState();
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState("");


  var apiKey = "a7dcb4960d5e300839a3e8e8463b9694";
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;

  const searchLocation = (event) => {
    if (event.key === "Enter") {
      axios.get(url).then((response) => {
        console.clear();
        setData(response.data);
        console.log(response.data);
        setWeather(response.data.weather);
        setErrorMessage("");

      }).catch((err) => {
        console.log(err);
        setErrorMessage("please enter a new location");
        setData({});
      });
      setLocation("");
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Find a weather today</h1>
          {errorMessage}
          <input
            value={location}
            onChange={event => setLocation(event.target.value)}
            placeholder="Enter location"
            onKeyDown={searchLocation}
            type="text"
          />
        </div>
        <div className={styles.description}>
          {
            weather && weather.map((w, i) => {
              return (
                <div key={i}>
                  <h3>Description</h3>
                  <div>{w.description}</div>
                </div>
              )
            })
          }{
            data && <div>
              <div>
                <h3>Temperature</h3>
                <div><span>{data.main.temp}</span>℃</div>
              </div>
              <div>
                <h3>Feels like</h3>
                <div><span>{data.main.feels_like}</span>℃</div>
              </div>
              <div>
                <h3>Wind speed</h3>
                <div><span>{data.wind.speed}</span>m/s</div>
              </div>
            </div>
          }
        </div>
      </main>
    </>
  )
}
